- name: start kafka
  service: name=kafka state=started enabled=yes

- name: restart kafka
  service: name=kafka state=restarted enabled=yes
- name: start zookeeper
  service: name=zookeeper state=started enabled=yes

- name: restart zookeeper
  service: name=zookeeper state=restarted enabled=yes
